### ISSUE TITLE
Can you use a buffer as an input file?

### ISSUE THREAD

**Issue by lucas-aragno** [talklittle/ffmpex#11]
Hi! I'm wondering if you are able to use a buffer / in memory file on `add_input_file` or it's only meant for filepath ( on cdn/file system) ? my elixir is kinda rusty but i like this project!

**Comment by talklittle** [comment]
It currently works with file paths, since the library passes the arguments to the `ffmpeg` command line program. You might be able to use different types of streams somehow but I have not looked into this. It may likely require changes to the library (pull requests welcome).

**Comment by lucas-aragno** [comment]
I'll take a look into that i might come up with some solution! thanks for the answer :) closing the issue for now
