### ISSUE TITLE
Add a { :error, :invalid_file } for when the file is not a file with duration

### ISSUE THREAD

**Issue by d3bbie** [talklittle/ffmpex#18]
Hi,
I am making a media center software. I decided to use FFmpex as my interface to get metadata from the files in storage. 
It would make things very much easier for me if there were error messages for when thigns went wronga and what happened. Then I could match on those messages. Instead now, right now I have to make sure the file exists and that it actually is a media file. For example right now if I do a:
`FFprobe.streams("mix.exs")`
A error saying "** (MatchError) no match of right hand side value:
`{"{\n\n}\n", 1}`" is raised. Something like { :error, :invalid_file } or just :invalid_file would be much better. 
Also if I tried to do a `FFprobe.streams("non_existing_file.mkv")` I would like a error message saying something like  { :error, :no_such_file } or  :no_such_file. This feature request applies to format_names/1 and format/1 too, not just streams/1. 
Thanks for your library

**Comment by d3bbie** [comment]
Also I dislike the fact that if FFmpeg isnt installed the library fails. I think it should instead raise a proper error. I have looked into the source code of the library and implemented this. I will also to try to come up with a pull request to fix this issue.

**Comment by talklittle** [comment]
Fixed in #19 thanks!
