### ISSUE TITLE
-c:a copy -c:b copy not properly handled ?

### ISSUE THREAD

**Issue by bougueil** [talklittle/ffmpex#27]
FFmpex.new_command
      |> add_global_option(option_y())
      |> add_input_file("small.mp4")
        |> add_stream_specifier(stream_type: :audio)
        |> add_stream_option(option_c("copy"))
        |> add_stream_specifier(stream_type: :video)
        |> add_stream_option(option_c("copy"))
      |> add_output_file("small2.mp4")
generates wrong cmd args ["-y", "-c:v", "copy", "-c:a", "copy", "-i", "small.mp4", "small2.mp4"]

a working cmd args are ["-y", "-i", "small.mp4", "-c:v", "copy", "-c:a", "copy", "small2.mp4"]

**Comment by talklittle** [comment]
Probably because of this:

https://github.com/talklittle/ffmpex/blob/b3053e2824bffe12432e4fd0c4a5cc1f493dd7f9/lib/ffmpex.ex#L8-L12

So do

```
FFmpex.new_command
  |> add_global_option(option_y())
  |> add_input_file("small.mp4")
  |> add_output_file("small2.mp4")
    |> add_stream_specifier(stream_type: :audio)
    |> add_stream_option(option_c("copy"))
    |> add_stream_specifier(stream_type: :video)
    |> add_stream_option(option_c("copy"))
```

**Comment by bougueil** [comment]
I miss it completely,
no way to let it appear in the README ? 
thanks !
