### ISSUE TITLE
Add a way to get the value outputted from ffmpeg

### ISSUE THREAD

**Issue by hammsvietro** [talklittle/ffmpex#30]
Before anything, thanks!  I've been using this tool and it works great! 

The only issue that I'm encountering, is that I really want to get the output value from ffmpeg directly to a variable, currently I running the command, reading it from the created file and deleting it afterwards.

By using `ffmpeg -i sample.mp3 -f wav -`  it is possible to output the converted content to stdout.

Similar to #23 it would be really useful to get the data without the need to generate temporary files

**Comment by talklittle** [comment]
Fixed in #31
