### ISSUE TITLE
I can't figure out how to make a video from a list of png files

### ISSUE THREAD

**Issue by David-Gil** [talklittle/ffmpex#35]
Hi!

I'd like to know how to make a video from a list of png files with ffmpex, but from the documentation is hard to figure it out.

Cheers,

David Gil

**Comment by talklittle** [comment]
If you post your **ffmpeg command-line command** here, we can help rewrite it into Elixir/ffmpex.

**Comment by prtngn** [comment]
Hi. How I can use pattern_type command?
```
ffmpeg -f image2 -r 24 -pattern_type glob -i '*.jpg' -s 320x240 -c:v libx264 -pix_fmt yuv420p out.mp4
```
