### ISSUE TITLE
Rambo and Rust error when trying to execute command

### ISSUE THREAD

**Issue by datpt11** [talklittle/ffmpex#45]
When I run executecuse I get this error

** (RuntimeError) Rambo does not ship with binaries for your environment.

    aarch64-unknown-linux-musl detected

Install the Rust compiler so a binary can be prepared for you.

    lib/mix/tasks/compile.rambo.ex:89: Mix.Tasks.Compile.Rambo.compile!/0
    lib/mix/tasks/compile.rambo.ex:51: Mix.Tasks.Compile.Rambo.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2

**Comment by talklittle** [comment]
Sounds like you need to [install Rust](https://www.rust-lang.org/tools/install).

**Comment by datpt11** [comment]
Why do I have to install rust?

**Comment by talklittle** [comment]
For [Rambo](https://github.com/jayjun/rambo), which this library uses to execute processes.

**Comment by datpt11** [comment]
If I install it on the server, I have to install rust, right?

**Comment by datpt11** [comment]
<img width="679" alt="Screenshot 2024-09-17 at 10 51 49 AM" src="https://github.com/user-attachments/assets/9ad8e008-4119-4aeb-aa7f-2ee9180a38b0">
<img width="346" alt="Screenshot 2024-09-17 at 10 51 04 AM" src="https://github.com/user-attachments/assets/bbd5cc72-5234-456d-8ebb-8889112e943e">

I have ffmpeg installed on my mac m1 pro. When I use System.find_executable("ffmpeg") it still returns nil.
