### ISSUE TITLE
File concatenation?

### ISSUE THREAD

**Issue by TrevorHinesley** [talklittle/ffmpex#5]
Is it possible to use [Concatenate](https://trac.ffmpeg.org/wiki/Concatenate) to combine audio files? Such as for watermarking and such?

**Comment by talklittle** [comment]
@TrevorHinesley Yes, this library is a direct wrapper for the CLI arguments, so you can convert the example on that page:

    ffmpeg -f concat -i mylist.txt -c copy output

into:

```elixir
import FFmpex
use FFmpex.Options

:ok =
  FFmpex.new_command
  |> add_input_file("/path/to/mylist.txt")
    |> add_file_option(option_f("concat"))
  |> add_output_file("/path/to/output")
    |> add_file_option(option_codec("copy"))  # -c and -codec are aliases
  |> execute
```

By the way, sorry for late reply, it seems GitHub didn't auto-enable notifications on this repository for some reason; it usually does.
