### ISSUE TITLE
Feature requests libavformat

### ISSUE THREAD

**Issue by johnwahba** [talklittle/ffmpex#6]
Would be awesome if ffmpex supported libavformat flags:

https://www.ffmpeg.org/ffmpeg-formats.html#Format-Options

**Comment by talklittle** [comment]
Any flags specifically? Also I gladly welcome pull requests to add new sets of options. :smile: 

By the way, sorry for late reply, it seems GitHub didn't auto-enable notifications on this repository for some reason; it usually does.
